config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants, only: %i[index show new create] do
    resources :reviews, only: %i[new create]
  end
  resources :reviews, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  CATEGORY = %w[chinese italian japanese french belgian].freeze

  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true, inclusion: { in: Restaurant::CATEGORY }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
  validates :rating, presence: true, inclusion: { in: (0..5) }, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  # before_action :set_restaurant, only: [:show, :create]

  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(strong_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def strong_params
    params.require(:restaurant).permit(:name, :address, :category)
  end

  # def set_restaurant
  #   @restaurant = Restaurant.find(params[:id])
  # end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(strong_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to restaurant_path(@review.restaurant)
  end

  private

  def strong_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for @restaurant do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :category, collection: Restaurant::CATEGORY, include_blank: false %>
    <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/restaurants/index.html.erb
<div class="container">
  <h1>Restaurants</h1>
  <div class="my-3 bg-info p-3">
    <%= link_to '🍽️ Add restaurant', new_restaurant_path %>
  </div>
  <% @restaurants.each do |restaurant| %>
    <div class="card mb-2 p-3">
      <h3><%= link_to restaurant.name, restaurant_path(restaurant) %></h3>
      <p class="my-0"><%= restaurant.address %></p>
    </div>
  <% end %>
</div>

app/views/restaurants/new.html.erb
<div class="container">
  <h1>Adding new restaurant</h1>
  <%= render 'form' %>
  <br>
  <%= link_to '◀ Back', restaurants_path %>
</div>

app/views/restaurants/show.html.erb
<div style="padding: 32px; background: linear-gradient(130deg, rgba(255, 255, 255, 1) 15%, rgba(255, 255, 255, 0) 70%), url('https://source.unsplash.com/random/?food'); background-size: cover">
<h1><%= @restaurant.name %></h1>
<h3><%= @restaurant.category %></h3>
<p><%= @restaurant.address %></p>
</div>

<div class='container'>
  <div class="my-3 bg-info p-3">
    <%= link_to '◀ Back', restaurants_path %>
    <span> | </span>
    <%= link_to '📝 Add a Review', new_restaurant_review_path(@restaurant) %>
  </div>
  <% if @restaurant.reviews.any? %>
    <% @restaurant.reviews.each do |review| %>
      <div class="card p-3 mt-2">
        <p><%= '⭐' * review.rating %></p>
        <p><%= review.content %></p>
        <%= link_to 'delete', review_path(review), method:'delete' %>
      </div>
    <% end %>
  <% else %>
    <div class="card p-3 mt-2">
      <%= link_to 'Be the first one to review this restaurant!', new_restaurant_review_path(@restaurant) %>
    </div>
  <% end %>
</div>

app/views/reviews/_form.html.erb
<%= simple_form_for [@restaurant, @review] do |f| %>
    <%= f.input :content %>
    <%= f.input :rating %>
    <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/reviews/new.html.erb
<div class="container">
  <h1>Adding new restaurant</h1>
  <%= render 'reviews/form' %>
  <br>
  <%= link_to '◀ Back', restaurants_path %>
</div>